controller_list:
  - name: fake_elfin_arm_controller
    joints:
      - elfin_joint1
      - elfin_joint2
      - elfin_joint3
      - elfin_joint4
      - elfin_joint5
      - elfin_joint6
  - name: fake_robotiq_3f_controller
    joints:
      - robotiq_palm_finger_1_joint
      - robotiq_finger_1_joint_1
      - robotiq_finger_1_joint_2
      - robotiq_finger_1_joint_3
      - robotiq_palm_finger_2_joint
      - robotiq_finger_2_joint_1
      - robotiq_finger_2_joint_2
      - robotiq_finger_2_joint_3
      - robotiq_finger_middle_joint_1
      - robotiq_finger_middle_joint_2
      - robotiq_finger_middle_joint_3
initial:  # Define initial robot poses.
  - group: elfin_arm
    pose: all_zero